if(typeof Math.imul == "undefined" || (Math.imul(0xffffffff,5) == 0)) {
    Math.imul = function (a, b) {
        var ah  = (a >>> 16) & 0xffff;
        var al = a & 0xffff;
        var bh  = (b >>> 16) & 0xffff;
        var bl = b & 0xffff;
        // the shift by 0 fixes the sign on the high part
        // the final |0 converts the unsigned value into a signed value
        return ((al * bl) + (((ah * bl + al * bh) << 16) >>> 0)|0);
    }
}


var f;
function t(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}var ca="closure_uid_"+(1E9*Math.random()>>>0),da=0;function ea(a,b){for(var c in a)b.call(void 0,a[c],c,a)};function ga(a,b){null!=a&&this.append.apply(this,arguments)}f=ga.prototype;f.Ia="";f.set=function(a){this.Ia=""+a};f.append=function(a,b,c){this.Ia+=a;if(null!=b)for(var d=1;d<arguments.length;d++)this.Ia+=arguments[d];return this};f.clear=function(){this.Ia=""};f.toString=function(){return this.Ia};var ha;if("undefined"===typeof ia)var ia=function(){throw Error("No *print-fn* fn set for evaluation environment");};if("undefined"===typeof ka)var ka=function(){throw Error("No *print-err-fn* fn set for evaluation environment");};var la=null;if("undefined"===typeof ma)var ma=null;function x(a){return null!=a&&!1!==a}function na(a){return a instanceof Array}function z(a,b){return a[t(null==b?null:b)]?!0:a._?!0:!1}
function A(a,b){var c=null==b?null:b.constructor,c=x(x(c)?c.nb:c)?c.Za:t(b);return Error(["No protocol method ",a," defined for type ",c,": ",b].join(""))}function pa(a){var b=a.Za;return x(b)?b:""+C(a)}var ra="undefined"!==typeof Symbol&&"function"===t(Symbol)?Symbol.iterator:"@@iterator";function E(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}
function ta(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 1:return ua(arguments[0]);case 2:return ua(arguments[1]);default:throw Error([C("Invalid arity: "),C(b.length)].join(""));}}function xa(a){return ua(a)}function ua(a){function b(a,b){a.push(b);return a}var c=[];return ya?ya(b,c,a):za.call(null,b,c,a)}function Aa(){}
var Ba=function Ba(b){if(null!=b&&null!=b.U)return b.U(b);var c=Ba[t(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=Ba._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw A("ICounted.-count",b);},Ca=function Ca(b,c){if(null!=b&&null!=b.L)return b.L(b,c);var d=Ca[t(null==b?null:b)];if(null!=d)return d.b?d.b(b,c):d.call(null,b,c);d=Ca._;if(null!=d)return d.b?d.b(b,c):d.call(null,b,c);throw A("ICollection.-conj",b);};function Da(){}
var F=function F(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 2:return F.b(arguments[0],arguments[1]);case 3:return F.g(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(c.length)].join(""));}};
F.b=function(a,b){if(null!=a&&null!=a.W)return a.W(a,b);var c=F[t(null==a?null:a)];if(null!=c)return c.b?c.b(a,b):c.call(null,a,b);c=F._;if(null!=c)return c.b?c.b(a,b):c.call(null,a,b);throw A("IIndexed.-nth",a);};F.g=function(a,b,c){if(null!=a&&null!=a.ba)return a.ba(a,b,c);var d=F[t(null==a?null:a)];if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);d=F._;if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);throw A("IIndexed.-nth",a);};F.T=3;
var G=function G(b){if(null!=b&&null!=b.S)return b.S(b);var c=G[t(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=G._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw A("ISeq.-first",b);},H=function H(b){if(null!=b&&null!=b.Z)return b.Z(b);var c=H[t(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=H._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw A("ISeq.-rest",b);};function Ea(){}function Ga(){}
var I=function I(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 2:return I.b(arguments[0],arguments[1]);case 3:return I.g(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(c.length)].join(""));}};
I.b=function(a,b){if(null!=a&&null!=a.N)return a.N(a,b);var c=I[t(null==a?null:a)];if(null!=c)return c.b?c.b(a,b):c.call(null,a,b);c=I._;if(null!=c)return c.b?c.b(a,b):c.call(null,a,b);throw A("ILookup.-lookup",a);};I.g=function(a,b,c){if(null!=a&&null!=a.F)return a.F(a,b,c);var d=I[t(null==a?null:a)];if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);d=I._;if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);throw A("ILookup.-lookup",a);};I.T=3;
var Ha=function Ha(b,c,d){if(null!=b&&null!=b.Pa)return b.Pa(b,c,d);var e=Ha[t(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=Ha._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw A("IAssociative.-assoc",b);};function Ia(){}function Ja(){}
var La=function La(b){if(null!=b&&null!=b.fb)return b.fb();var c=La[t(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=La._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw A("IMapEntry.-key",b);},Ma=function Ma(b){if(null!=b&&null!=b.gb)return b.gb();var c=Ma[t(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=Ma._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw A("IMapEntry.-val",b);};function Na(){}
var Oa=function Oa(b,c,d){if(null!=b&&null!=b.ib)return b.ib(b,c,d);var e=Oa[t(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=Oa._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw A("IVector.-assoc-n",b);};function Pa(){}
var Qa=function Qa(b){if(null!=b&&null!=b.H)return b.H(b);var c=Qa[t(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=Qa._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw A("IMeta.-meta",b);},Ra=function Ra(b,c){if(null!=b&&null!=b.I)return b.I(b,c);var d=Ra[t(null==b?null:b)];if(null!=d)return d.b?d.b(b,c):d.call(null,b,c);d=Ra._;if(null!=d)return d.b?d.b(b,c):d.call(null,b,c);throw A("IWithMeta.-with-meta",b);};function Sa(){}
var Ta=function Ta(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 2:return Ta.b(arguments[0],arguments[1]);case 3:return Ta.g(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(c.length)].join(""));}};
Ta.b=function(a,b){if(null!=a&&null!=a.P)return a.P(a,b);var c=Ta[t(null==a?null:a)];if(null!=c)return c.b?c.b(a,b):c.call(null,a,b);c=Ta._;if(null!=c)return c.b?c.b(a,b):c.call(null,a,b);throw A("IReduce.-reduce",a);};Ta.g=function(a,b,c){if(null!=a&&null!=a.R)return a.R(a,b,c);var d=Ta[t(null==a?null:a)];if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);d=Ta._;if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);throw A("IReduce.-reduce",a);};Ta.T=3;
var Ua=function Ua(b,c){if(null!=b&&null!=b.o)return b.o(b,c);var d=Ua[t(null==b?null:b)];if(null!=d)return d.b?d.b(b,c):d.call(null,b,c);d=Ua._;if(null!=d)return d.b?d.b(b,c):d.call(null,b,c);throw A("IEquiv.-equiv",b);},Va=function Va(b){if(null!=b&&null!=b.D)return b.D(b);var c=Va[t(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=Va._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw A("IHash.-hash",b);};function Wa(){}
var Xa=function Xa(b){if(null!=b&&null!=b.M)return b.M(b);var c=Xa[t(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=Xa._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw A("ISeqable.-seq",b);};function Ya(){}function Za(){}
var K=function K(b,c){if(null!=b&&null!=b.mb)return b.mb(0,c);var d=K[t(null==b?null:b)];if(null!=d)return d.b?d.b(b,c):d.call(null,b,c);d=K._;if(null!=d)return d.b?d.b(b,c):d.call(null,b,c);throw A("IWriter.-write",b);},$a=function $a(b,c,d){if(null!=b&&null!=b.C)return b.C(b,c,d);var e=$a[t(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=$a._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw A("IPrintWithWriter.-pr-writer",b);},cb=function cb(b){if(null!=b&&null!=
b.Ua)return b.Ua(b);var c=cb[t(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=cb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw A("IEditableCollection.-as-transient",b);},db=function db(b,c){if(null!=b&&null!=b.Xa)return b.Xa(b,c);var d=db[t(null==b?null:b)];if(null!=d)return d.b?d.b(b,c):d.call(null,b,c);d=db._;if(null!=d)return d.b?d.b(b,c):d.call(null,b,c);throw A("ITransientCollection.-conj!",b);},eb=function eb(b){if(null!=b&&null!=b.Ya)return b.Ya(b);var c=eb[t(null==b?
null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=eb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw A("ITransientCollection.-persistent!",b);},fb=function fb(b,c,d){if(null!=b&&null!=b.Qa)return b.Qa(b,c,d);var e=fb[t(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=fb._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw A("ITransientAssociative.-assoc!",b);},gb=function gb(b,c,d){if(null!=b&&null!=b.lb)return b.lb(0,c,d);var e=gb[t(null==b?null:b)];if(null!=
e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=gb._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw A("ITransientVector.-assoc-n!",b);},hb=function hb(b){if(null!=b&&null!=b.kb)return b.kb();var c=hb[t(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=hb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw A("IChunk.-drop-first",b);},ib=function ib(b){if(null!=b&&null!=b.cb)return b.cb(b);var c=ib[t(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=ib._;if(null!=c)return c.c?
c.c(b):c.call(null,b);throw A("IChunkedSeq.-chunked-first",b);},jb=function jb(b){if(null!=b&&null!=b.eb)return b.eb(b);var c=jb[t(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=jb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw A("IChunkedSeq.-chunked-rest",b);},kb=function kb(b){if(null!=b&&null!=b.bb)return b.bb(b);var c=kb[t(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=kb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw A("IChunkedNext.-chunked-next",b);
},mb=function mb(b){if(null!=b&&null!=b.Ca)return b.Ca(b);var c=mb[t(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=mb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw A("IIterable.-iterator",b);};function nb(a){this.Cb=a;this.j=1073741824;this.v=0}nb.prototype.mb=function(a,b){return this.Cb.append(b)};function ob(a){var b=new ga;a.C(null,new nb(b),new pb(null,5,[qb,!0,rb,!0,sb,!1,tb,!1,ub,null],null));return""+C(b)}
var vb="undefined"!==typeof Math.imul&&0!==Math.imul(4294967295,5)?function(a,b){return Math.imul(a,b)}:function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0};function wb(a){a=vb(a|0,-862048943);return vb(a<<15|a>>>-15,461845907)}function yb(a,b){var c=(a|0)^(b|0);return vb(c<<13|c>>>-13,5)+-430675100|0}function zb(a,b){var c=(a|0)^b,c=vb(c^c>>>16,-2048144789),c=vb(c^c>>>13,-1028477387);return c^c>>>16}
function Ab(a){var b;a:{b=1;for(var c=0;;)if(b<a.length){var d=b+2,c=yb(c,wb(a.charCodeAt(b-1)|a.charCodeAt(b)<<16));b=d}else{b=c;break a}}b=1===(a.length&1)?b^wb(a.charCodeAt(a.length-1)):b;return zb(b,vb(2,a.length))}var Bb={},Cb=0;function Db(a){255<Cb&&(Bb={},Cb=0);var b=Bb[a];if("number"!==typeof b){a:if(null!=a)if(b=a.length,0<b)for(var c=0,d=0;;)if(c<b)var e=c+1,d=vb(31,d)+a.charCodeAt(c),c=e;else{b=d;break a}else b=0;else b=0;Bb[a]=b;Cb+=1}return a=b}
function Eb(a){null!=a&&(a.j&4194304||a.Fb)?a=a.D(null):"number"===typeof a?a=Math.floor(a)%2147483647:!0===a?a=1:!1===a?a=0:"string"===typeof a?(a=Db(a),0!==a&&(a=wb(a),a=yb(0,a),a=zb(a,4))):a=a instanceof Date?a.valueOf():null==a?0:Va(a);return a}function Fb(a,b){return a^b+2654435769+(a<<6)+(a>>2)}function Gb(a,b,c,d,e){this.Ta=a;this.name=b;this.Ha=c;this.Ma=d;this.ea=e;this.j=2154168321;this.v=4096}f=Gb.prototype;f.toString=function(){return this.Ha};f.equiv=function(a){return this.o(null,a)};
f.o=function(a,b){return b instanceof Gb?this.Ha===b.Ha:!1};f.call=function(){function a(a,b,c){return Hb?Hb(b,this,c):Ib.call(null,b,this,c)}function b(a,b){return Jb?Jb(b,this):Ib.call(null,b,this)}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,0,e);case 3:return a.call(this,0,e,g)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.g=a;return c}();f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};
f.c=function(a){return Jb?Jb(a,this):Ib.call(null,a,this)};f.b=function(a,b){return Hb?Hb(a,this,b):Ib.call(null,a,this,b)};f.H=function(){return this.ea};f.I=function(a,b){return new Gb(this.Ta,this.name,this.Ha,this.Ma,b)};f.D=function(){var a=this.Ma;return null!=a?a:this.Ma=a=Fb(Ab(this.name),Db(this.Ta))};f.C=function(a,b){return K(b,this.Ha)};
function L(a){if(null==a)return null;if(null!=a&&(a.j&8388608||a.yb))return a.M(null);if(na(a)||"string"===typeof a)return 0===a.length?null:new M(a,0);if(z(Wa,a))return Xa(a);throw Error([C(a),C(" is not ISeqable")].join(""));}function N(a){if(null==a)return null;if(null!=a&&(a.j&64||a.hb))return a.S(null);a=L(a);return null==a?null:G(a)}function Kb(a){return null!=a?null!=a&&(a.j&64||a.hb)?a.Z(null):(a=L(a))?H(a):O:O}
function P(a){return null==a?null:null!=a&&(a.j&128||a.Wa)?a.X(null):L(Kb(a))}var Q=function Q(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 1:return Q.c(arguments[0]);case 2:return Q.b(arguments[0],arguments[1]);default:return Q.A(arguments[0],arguments[1],new M(c.slice(2),0))}};Q.c=function(){return!0};Q.b=function(a,b){return null==a?null==b:a===b||Ua(a,b)};
Q.A=function(a,b,c){for(;;)if(Q.b(a,b))if(P(c))a=b,b=N(c),c=P(c);else return Q.b(b,N(c));else return!1};Q.J=function(a){var b=N(a),c=P(a);a=N(c);c=P(c);return Q.A(b,a,c)};Q.T=2;function Lb(a){this.u=a}Lb.prototype.next=function(){if(null!=this.u){var a=N(this.u);this.u=P(this.u);return{value:a,done:!1}}return{value:null,done:!0}};function S(a){return new Lb(L(a))}function Mb(a,b){var c=wb(a),c=yb(0,c);return zb(c,b)}
function Nb(a){var b=0,c=1;for(a=L(a);;)if(null!=a)b+=1,c=vb(31,c)+Eb(N(a))|0,a=P(a);else return Mb(c,b)}var Ob=Mb(1,0);function Pb(a){var b=0,c=0;for(a=L(a);;)if(null!=a)b+=1,c=c+Eb(N(a))|0,a=P(a);else return Mb(c,b)}var Qb=Mb(0,0);Aa["null"]=!0;Ba["null"]=function(){return 0};Date.prototype.o=function(a,b){return b instanceof Date&&this.valueOf()===b.valueOf()};Ua.number=function(a,b){return a===b};Pa["function"]=!0;Qa["function"]=function(){return null};Va._=function(a){return a[ca]||(a[ca]=++da)};
function Rb(a,b){var c=Ba(a);if(0===c)return b.B?b.B():b.call(null);for(var d=F.b(a,0),e=1;;)if(e<c)var g=F.b(a,e),d=b.b?b.b(d,g):b.call(null,d,g),e=e+1;else return d}function Sb(a,b,c){var d=Ba(a),e=c;for(c=0;;)if(c<d){var g=F.b(a,c),e=b.b?b.b(e,g):b.call(null,e,g);c+=1}else return e}function Tb(a,b){var c=a.length;if(0===a.length)return b.B?b.B():b.call(null);for(var d=a[0],e=1;;)if(e<c)var g=a[e],d=b.b?b.b(d,g):b.call(null,d,g),e=e+1;else return d}
function Vb(a,b,c){var d=a.length,e=c;for(c=0;;)if(c<d){var g=a[c],e=b.b?b.b(e,g):b.call(null,e,g);c+=1}else return e}function Wb(a,b,c,d){for(var e=a.length;;)if(d<e){var g=a[d];c=b.b?b.b(c,g):b.call(null,c,g);d+=1}else return c}function Xb(a){return null!=a?a.j&2||a.pb?!0:a.j?!1:z(Aa,a):z(Aa,a)}function Yb(a,b){this.a=a;this.i=b}Yb.prototype.fa=function(){return this.i<this.a.length};Yb.prototype.next=function(){var a=this.a[this.i];this.i+=1;return a};
function M(a,b){this.a=a;this.i=b;this.j=166199550;this.v=8192}f=M.prototype;f.toString=function(){return ob(this)};f.equiv=function(a){return this.o(null,a)};f.W=function(a,b){var c=b+this.i;return c<this.a.length?this.a[c]:null};f.ba=function(a,b,c){a=b+this.i;return a<this.a.length?this.a[a]:c};f.Ca=function(){return new Yb(this.a,this.i)};f.X=function(){return this.i+1<this.a.length?new M(this.a,this.i+1):null};f.U=function(){var a=this.a.length-this.i;return 0>a?0:a};f.D=function(){return Nb(this)};
f.o=function(a,b){return Zb.b?Zb.b(this,b):Zb.call(null,this,b)};f.P=function(a,b){return Wb(this.a,b,this.a[this.i],this.i+1)};f.R=function(a,b,c){return Wb(this.a,b,c,this.i)};f.S=function(){return this.a[this.i]};f.Z=function(){return this.i+1<this.a.length?new M(this.a,this.i+1):O};f.M=function(){return this.i<this.a.length?this:null};f.L=function(a,b){return U.b?U.b(b,this):U.call(null,b,this)};M.prototype[ra]=function(){return S(this)};function $b(a,b){return b<a.length?new M(a,b):null}
function ac(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 1:return $b(arguments[0],0);case 2:return $b(arguments[0],arguments[1]);default:throw Error([C("Invalid arity: "),C(b.length)].join(""));}}Ua._=function(a,b){return a===b};
var bc=function bc(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 0:return bc.B();case 1:return bc.c(arguments[0]);case 2:return bc.b(arguments[0],arguments[1]);default:return bc.A(arguments[0],arguments[1],new M(c.slice(2),0))}};bc.B=function(){return cc};bc.c=function(a){return a};bc.b=function(a,b){return null!=a?Ca(a,b):Ca(O,b)};bc.A=function(a,b,c){for(;;)if(x(c))a=bc.b(a,b),b=N(c),c=P(c);else return bc.b(a,b)};
bc.J=function(a){var b=N(a),c=P(a);a=N(c);c=P(c);return bc.A(b,a,c)};bc.T=2;function dc(a){if(null!=a)if(null!=a&&(a.j&2||a.pb))a=a.U(null);else if(na(a))a=a.length;else if("string"===typeof a)a=a.length;else if(null!=a&&(a.j&8388608||a.yb))a:{a=L(a);for(var b=0;;){if(Xb(a)){a=b+Ba(a);break a}a=P(a);b+=1}}else a=Ba(a);else a=0;return a}
function ec(a,b){for(var c=null;;){if(null==a)return c;if(0===b)return L(a)?N(a):c;var d=a;if(null!=d?d.j&16||d.rb||(d.j?0:z(Da,d)):z(Da,d))return F.g(a,b,c);if(L(a)){var d=P(a),e=b-1;a=d;b=e}else return c}}
function fc(a,b){if("number"!==typeof b)throw Error("index argument to nth must be a number.");if(null==a)return null;if(null!=a&&(a.j&16||a.rb))return a.ba(null,b,null);if(na(a))return b<a.length?a[b]:null;if("string"===typeof a)return b<a.length?a.charAt(b):null;if(null!=a&&(a.j&64||a.hb))return ec(a,b);if(z(Da,a))return F.b(a,b);throw Error([C("nth not supported on this type "),C(pa(null==a?null:a.constructor))].join(""));}
function Ib(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 2:return Jb(arguments[0],arguments[1]);case 3:return Hb(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(b.length)].join(""));}}function Jb(a,b){return null==a?null:null!=a&&(a.j&256||a.sb)?a.N(null,b):na(a)?b<a.length?a[b|0]:null:"string"===typeof a?b<a.length?a[b|0]:null:z(Ga,a)?I.b(a,b):null}
function Hb(a,b,c){return null!=a?null!=a&&(a.j&256||a.sb)?a.F(null,b,c):na(a)?b<a.length?a[b]:c:"string"===typeof a?b<a.length?a[b]:c:z(Ga,a)?I.g(a,b,c):c:c}var gc=function gc(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 3:return gc.g(arguments[0],arguments[1],arguments[2]);default:return gc.A(arguments[0],arguments[1],arguments[2],new M(c.slice(3),0))}};
gc.g=function(a,b,c){if(null!=a)a=Ha(a,b,c);else a:{a=[b];c=[c];b=a.length;var d=0,e;for(e=cb(hc);;)if(d<b){var g=d+1;e=e.Qa(null,a[d],c[d]);d=g}else{a=eb(e);break a}}return a};gc.A=function(a,b,c,d){for(;;)if(a=gc.g(a,b,c),x(d))b=N(d),c=N(P(d)),d=P(P(d));else return a};gc.J=function(a){var b=N(a),c=P(a);a=N(c);var d=P(c),c=N(d),d=P(d);return gc.A(b,a,c,d)};gc.T=3;function ic(a,b){this.f=a;this.m=b;this.j=393217;this.v=0}f=ic.prototype;f.H=function(){return this.m};
f.I=function(a,b){return new ic(this.f,b)};
f.call=function(){function a(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,w,D,J,ba){a=this;return jc.Va?jc.Va(a.f,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,w,D,J,ba):jc.call(null,a.f,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,w,D,J,ba)}function b(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,w,D,J){a=this;return a.f.xa?a.f.xa(b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,w,D,J):a.f.call(null,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,w,D,J)}function c(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,w,D){a=this;return a.f.wa?a.f.wa(b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,
w,D):a.f.call(null,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,w,D)}function d(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,w){a=this;return a.f.va?a.f.va(b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,w):a.f.call(null,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,w)}function e(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B){a=this;return a.f.ua?a.f.ua(b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B):a.f.call(null,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B)}function g(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y){a=this;return a.f.ta?a.f.ta(b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y):a.f.call(null,
b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y)}function h(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v){a=this;return a.f.sa?a.f.sa(b,c,d,e,g,h,k,l,m,n,p,q,r,u,v):a.f.call(null,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v)}function k(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u){a=this;return a.f.ra?a.f.ra(b,c,d,e,g,h,k,l,m,n,p,q,r,u):a.f.call(null,b,c,d,e,g,h,k,l,m,n,p,q,r,u)}function l(a,b,c,d,e,g,h,k,l,m,n,p,q,r){a=this;return a.f.qa?a.f.qa(b,c,d,e,g,h,k,l,m,n,p,q,r):a.f.call(null,b,c,d,e,g,h,k,l,m,n,p,q,r)}function m(a,b,c,d,e,g,h,k,l,m,n,p,q){a=this;
return a.f.pa?a.f.pa(b,c,d,e,g,h,k,l,m,n,p,q):a.f.call(null,b,c,d,e,g,h,k,l,m,n,p,q)}function n(a,b,c,d,e,g,h,k,l,m,n,p){a=this;return a.f.oa?a.f.oa(b,c,d,e,g,h,k,l,m,n,p):a.f.call(null,b,c,d,e,g,h,k,l,m,n,p)}function p(a,b,c,d,e,g,h,k,l,m,n){a=this;return a.f.na?a.f.na(b,c,d,e,g,h,k,l,m,n):a.f.call(null,b,c,d,e,g,h,k,l,m,n)}function q(a,b,c,d,e,g,h,k,l,m){a=this;return a.f.Ba?a.f.Ba(b,c,d,e,g,h,k,l,m):a.f.call(null,b,c,d,e,g,h,k,l,m)}function r(a,b,c,d,e,g,h,k,l){a=this;return a.f.Aa?a.f.Aa(b,c,
d,e,g,h,k,l):a.f.call(null,b,c,d,e,g,h,k,l)}function u(a,b,c,d,e,g,h,k){a=this;return a.f.za?a.f.za(b,c,d,e,g,h,k):a.f.call(null,b,c,d,e,g,h,k)}function v(a,b,c,d,e,g,h){a=this;return a.f.ya?a.f.ya(b,c,d,e,g,h):a.f.call(null,b,c,d,e,g,h)}function y(a,b,c,d,e,g){a=this;return a.f.Y?a.f.Y(b,c,d,e,g):a.f.call(null,b,c,d,e,g)}function B(a,b,c,d,e){a=this;return a.f.aa?a.f.aa(b,c,d,e):a.f.call(null,b,c,d,e)}function D(a,b,c,d){a=this;return a.f.g?a.f.g(b,c,d):a.f.call(null,b,c,d)}function J(a,b,c){a=this;
return a.f.b?a.f.b(b,c):a.f.call(null,b,c)}function ba(a,b){a=this;return a.f.c?a.f.c(b):a.f.call(null,b)}function bb(a){a=this;return a.f.B?a.f.B():a.f.call(null)}var w=null,w=function(w,R,T,W,aa,fa,ja,oa,qa,sa,va,Fa,Ka,wa,ab,lb,xb,Ub,qc,Mc,Id,oe){switch(arguments.length){case 1:return bb.call(this,w);case 2:return ba.call(this,w,R);case 3:return J.call(this,w,R,T);case 4:return D.call(this,w,R,T,W);case 5:return B.call(this,w,R,T,W,aa);case 6:return y.call(this,w,R,T,W,aa,fa);case 7:return v.call(this,
w,R,T,W,aa,fa,ja);case 8:return u.call(this,w,R,T,W,aa,fa,ja,oa);case 9:return r.call(this,w,R,T,W,aa,fa,ja,oa,qa);case 10:return q.call(this,w,R,T,W,aa,fa,ja,oa,qa,sa);case 11:return p.call(this,w,R,T,W,aa,fa,ja,oa,qa,sa,va);case 12:return n.call(this,w,R,T,W,aa,fa,ja,oa,qa,sa,va,Fa);case 13:return m.call(this,w,R,T,W,aa,fa,ja,oa,qa,sa,va,Fa,Ka);case 14:return l.call(this,w,R,T,W,aa,fa,ja,oa,qa,sa,va,Fa,Ka,wa);case 15:return k.call(this,w,R,T,W,aa,fa,ja,oa,qa,sa,va,Fa,Ka,wa,ab);case 16:return h.call(this,
w,R,T,W,aa,fa,ja,oa,qa,sa,va,Fa,Ka,wa,ab,lb);case 17:return g.call(this,w,R,T,W,aa,fa,ja,oa,qa,sa,va,Fa,Ka,wa,ab,lb,xb);case 18:return e.call(this,w,R,T,W,aa,fa,ja,oa,qa,sa,va,Fa,Ka,wa,ab,lb,xb,Ub);case 19:return d.call(this,w,R,T,W,aa,fa,ja,oa,qa,sa,va,Fa,Ka,wa,ab,lb,xb,Ub,qc);case 20:return c.call(this,w,R,T,W,aa,fa,ja,oa,qa,sa,va,Fa,Ka,wa,ab,lb,xb,Ub,qc,Mc);case 21:return b.call(this,w,R,T,W,aa,fa,ja,oa,qa,sa,va,Fa,Ka,wa,ab,lb,xb,Ub,qc,Mc,Id);case 22:return a.call(this,w,R,T,W,aa,fa,ja,oa,qa,sa,
va,Fa,Ka,wa,ab,lb,xb,Ub,qc,Mc,Id,oe)}throw Error("Invalid arity: "+arguments.length);};w.c=bb;w.b=ba;w.g=J;w.aa=D;w.Y=B;w.ya=y;w.za=v;w.Aa=u;w.Ba=r;w.na=q;w.oa=p;w.pa=n;w.qa=m;w.ra=l;w.sa=k;w.ta=h;w.ua=g;w.va=e;w.wa=d;w.xa=c;w.qb=b;w.Va=a;return w}();f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.B=function(){return this.f.B?this.f.B():this.f.call(null)};f.c=function(a){return this.f.c?this.f.c(a):this.f.call(null,a)};
f.b=function(a,b){return this.f.b?this.f.b(a,b):this.f.call(null,a,b)};f.g=function(a,b,c){return this.f.g?this.f.g(a,b,c):this.f.call(null,a,b,c)};f.aa=function(a,b,c,d){return this.f.aa?this.f.aa(a,b,c,d):this.f.call(null,a,b,c,d)};f.Y=function(a,b,c,d,e){return this.f.Y?this.f.Y(a,b,c,d,e):this.f.call(null,a,b,c,d,e)};f.ya=function(a,b,c,d,e,g){return this.f.ya?this.f.ya(a,b,c,d,e,g):this.f.call(null,a,b,c,d,e,g)};
f.za=function(a,b,c,d,e,g,h){return this.f.za?this.f.za(a,b,c,d,e,g,h):this.f.call(null,a,b,c,d,e,g,h)};f.Aa=function(a,b,c,d,e,g,h,k){return this.f.Aa?this.f.Aa(a,b,c,d,e,g,h,k):this.f.call(null,a,b,c,d,e,g,h,k)};f.Ba=function(a,b,c,d,e,g,h,k,l){return this.f.Ba?this.f.Ba(a,b,c,d,e,g,h,k,l):this.f.call(null,a,b,c,d,e,g,h,k,l)};f.na=function(a,b,c,d,e,g,h,k,l,m){return this.f.na?this.f.na(a,b,c,d,e,g,h,k,l,m):this.f.call(null,a,b,c,d,e,g,h,k,l,m)};
f.oa=function(a,b,c,d,e,g,h,k,l,m,n){return this.f.oa?this.f.oa(a,b,c,d,e,g,h,k,l,m,n):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n)};f.pa=function(a,b,c,d,e,g,h,k,l,m,n,p){return this.f.pa?this.f.pa(a,b,c,d,e,g,h,k,l,m,n,p):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,p)};f.qa=function(a,b,c,d,e,g,h,k,l,m,n,p,q){return this.f.qa?this.f.qa(a,b,c,d,e,g,h,k,l,m,n,p,q):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q)};
f.ra=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r){return this.f.ra?this.f.ra(a,b,c,d,e,g,h,k,l,m,n,p,q,r):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r)};f.sa=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u){return this.f.sa?this.f.sa(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,u)};f.ta=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v){return this.f.ta?this.f.ta(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v)};
f.ua=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y){return this.f.ua?this.f.ua(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y)};f.va=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B){return this.f.va?this.f.va(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B)};
f.wa=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D){return this.f.wa?this.f.wa(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D)};f.xa=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D,J){return this.f.xa?this.f.xa(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D,J):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D,J)};
f.qb=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D,J,ba){return jc.Va?jc.Va(this.f,a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D,J,ba):jc.call(null,this.f,a,b,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D,J,ba)};function kc(a,b){return"function"==t(a)?new ic(a,b):null==a?null:Ra(a,b)}function lc(a){var b=null!=a;return(b?null!=a?a.j&131072||a.vb||(a.j?0:z(Pa,a)):z(Pa,a):b)?Qa(a):null}function mc(a){return null!=a?a.j&16777216||a.Hb?!0:a.j?!1:z(Ya,a):z(Ya,a)}
function nc(a){return null==a?!1:null!=a?a.j&1024||a.tb?!0:a.j?!1:z(Ia,a):z(Ia,a)}function oc(a){return null!=a?a.j&16384||a.Ib?!0:a.j?!1:z(Na,a):z(Na,a)}function pc(a){return null!=a?a.v&512||a.Db?!0:!1:!1}function rc(a){var b=[];ea(a,function(a,b){return function(a,c){return b.push(c)}}(a,b));return b}function sc(a,b,c,d,e){for(;0!==e;)c[d]=a[b],d+=1,--e,b+=1}var tc={};function uc(a){return null==a?!1:!1===a?!1:!0}
function vc(a,b){var c=L(b);if(c){var d=N(c),c=P(c);return ya?ya(a,d,c):za.call(null,a,d,c)}return a.B?a.B():a.call(null)}function wc(a,b,c){for(c=L(c);;)if(c){var d=N(c);b=a.b?a.b(b,d):a.call(null,b,d);c=P(c)}else return b}
function za(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 2:return b=arguments[0],c=arguments[1],null!=c&&(c.j&524288||c.xb)?c.P(null,b):na(c)?Tb(c,b):"string"===typeof c?Tb(c,b):z(Sa,c)?Ta.b(c,b):vc(b,c);case 3:return ya(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(b.length)].join(""));}}
function ya(a,b,c){return null!=c&&(c.j&524288||c.xb)?c.R(null,a,b):na(c)?Vb(c,a,b):"string"===typeof c?Vb(c,a,b):z(Sa,c)?Ta.g(c,a,b):wc(a,b,c)}function xc(a){return a}function yc(a){a=(a-a%2)/2;return 0<=a?Math.floor(a):Math.ceil(a)}function zc(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}
var C=function C(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 0:return C.B();case 1:return C.c(arguments[0]);default:return C.A(arguments[0],new M(c.slice(1),0))}};C.B=function(){return""};C.c=function(a){return null==a?"":""+a};C.A=function(a,b){for(var c=new ga(""+C(a)),d=b;;)if(x(d))c=c.append(""+C(N(d))),d=P(d);else return c.toString()};C.J=function(a){var b=N(a);a=P(a);return C.A(b,a)};C.T=1;
function Zb(a,b){var c;if(mc(b))if(Xb(a)&&Xb(b)&&dc(a)!==dc(b))c=!1;else a:{c=L(a);for(var d=L(b);;){if(null==c){c=null==d;break a}if(null!=d&&Q.b(N(c),N(d)))c=P(c),d=P(d);else{c=!1;break a}}}else c=null;return uc(c)}function Ac(a,b,c,d,e){this.m=a;this.first=b;this.Da=c;this.count=d;this.l=e;this.j=65937646;this.v=8192}f=Ac.prototype;f.toString=function(){return ob(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.m};f.X=function(){return 1===this.count?null:this.Da};
f.U=function(){return this.count};f.D=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.P=function(a,b){return vc(b,this)};f.R=function(a,b,c){return wc(b,c,this)};f.S=function(){return this.first};f.Z=function(){return 1===this.count?O:this.Da};f.M=function(){return this};f.I=function(a,b){return new Ac(b,this.first,this.Da,this.count,this.l)};f.L=function(a,b){return new Ac(this.m,b,this,this.count+1,null)};Ac.prototype[ra]=function(){return S(this)};
function Bc(a){this.m=a;this.j=65937614;this.v=8192}f=Bc.prototype;f.toString=function(){return ob(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.m};f.X=function(){return null};f.U=function(){return 0};f.D=function(){return Ob};f.o=function(a,b){return(null!=b?b.j&33554432||b.Gb||(b.j?0:z(Za,b)):z(Za,b))||mc(b)?null==L(b):!1};f.P=function(a,b){return vc(b,this)};f.R=function(a,b,c){return wc(b,c,this)};f.S=function(){return null};f.Z=function(){return O};f.M=function(){return null};
f.I=function(a,b){return new Bc(b)};f.L=function(a,b){return new Ac(this.m,b,null,1,null)};var O=new Bc(null);Bc.prototype[ra]=function(){return S(this)};function Cc(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;a:{c=0<b.length?new M(b.slice(0),0):null;if(c instanceof M&&0===c.i)b=c.a;else b:for(b=[];;)if(null!=c)b.push(c.S(null)),c=c.X(null);else break b;for(var c=b.length,e=O;;)if(0<c)d=c-1,e=e.L(null,b[c-1]),c=d;else break a}return e}
function Dc(a,b,c,d){this.m=a;this.first=b;this.Da=c;this.l=d;this.j=65929452;this.v=8192}f=Dc.prototype;f.toString=function(){return ob(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.m};f.X=function(){return null==this.Da?null:L(this.Da)};f.D=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.P=function(a,b){return vc(b,this)};f.R=function(a,b,c){return wc(b,c,this)};f.S=function(){return this.first};
f.Z=function(){return null==this.Da?O:this.Da};f.M=function(){return this};f.I=function(a,b){return new Dc(b,this.first,this.Da,this.l)};f.L=function(a,b){return new Dc(null,b,this,null)};Dc.prototype[ra]=function(){return S(this)};function U(a,b){var c=null==b;return(c?c:null!=b&&(b.j&64||b.hb))?new Dc(null,a,b,null):new Dc(null,a,L(b),null)}function V(a,b,c,d){this.Ta=a;this.name=b;this.Fa=c;this.Ma=d;this.j=2153775105;this.v=4096}f=V.prototype;f.toString=function(){return[C(":"),C(this.Fa)].join("")};
f.equiv=function(a){return this.o(null,a)};f.o=function(a,b){return b instanceof V?this.Fa===b.Fa:!1};f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return Jb(c,this);case 3:return Hb(c,this,d)}throw Error("Invalid arity: "+arguments.length);};a.b=function(a,c){return Jb(c,this)};a.g=function(a,c,d){return Hb(c,this,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.c=function(a){return Jb(a,this)};
f.b=function(a,b){return Hb(a,this,b)};f.D=function(){var a=this.Ma;return null!=a?a:this.Ma=a=Fb(Ab(this.name),Db(this.Ta))+2654435769|0};f.C=function(a,b){return K(b,[C(":"),C(this.Fa)].join(""))};var Ec=function Ec(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 1:return Ec.c(arguments[0]);case 2:return Ec.b(arguments[0],arguments[1]);default:throw Error([C("Invalid arity: "),C(c.length)].join(""));}};
Ec.c=function(a){if(a instanceof V)return a;if(a instanceof Gb){var b;if(null!=a&&(a.v&4096||a.wb))b=a.Ta;else throw Error([C("Doesn't support namespace: "),C(a)].join(""));return new V(b,Fc.c?Fc.c(a):Fc.call(null,a),a.Ha,null)}return"string"===typeof a?(b=a.split("/"),2===b.length?new V(b[0],b[1],a,null):new V(null,b[0],a,null)):null};Ec.b=function(a,b){return new V(a,b,[C(x(a)?[C(a),C("/")].join(""):null),C(b)].join(""),null)};Ec.T=2;
function Gc(a,b,c,d){this.m=a;this.Oa=b;this.u=c;this.l=d;this.j=32374988;this.v=1}f=Gc.prototype;f.toString=function(){return ob(this)};f.equiv=function(a){return this.o(null,a)};function Hc(a){null!=a.Oa&&(a.u=a.Oa.B?a.Oa.B():a.Oa.call(null),a.Oa=null);return a.u}f.H=function(){return this.m};f.X=function(){Xa(this);return null==this.u?null:P(this.u)};f.D=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.P=function(a,b){return vc(b,this)};
f.R=function(a,b,c){return wc(b,c,this)};f.S=function(){Xa(this);return null==this.u?null:N(this.u)};f.Z=function(){Xa(this);return null!=this.u?Kb(this.u):O};f.M=function(){Hc(this);if(null==this.u)return null;for(var a=this.u;;)if(a instanceof Gc)a=Hc(a);else return this.u=a,L(this.u)};f.I=function(a,b){return new Gc(b,this.Oa,this.u,this.l)};f.L=function(a,b){return U(b,this)};Gc.prototype[ra]=function(){return S(this)};function Ic(a,b){this.ab=a;this.end=b;this.j=2;this.v=0}
Ic.prototype.add=function(a){this.ab[this.end]=a;return this.end+=1};Ic.prototype.ga=function(){var a=new Jc(this.ab,0,this.end);this.ab=null;return a};Ic.prototype.U=function(){return this.end};function Jc(a,b,c){this.a=a;this.K=b;this.end=c;this.j=524306;this.v=0}f=Jc.prototype;f.U=function(){return this.end-this.K};f.W=function(a,b){return this.a[this.K+b]};f.ba=function(a,b,c){return 0<=b&&b<this.end-this.K?this.a[this.K+b]:c};
f.kb=function(){if(this.K===this.end)throw Error("-drop-first of empty chunk");return new Jc(this.a,this.K+1,this.end)};f.P=function(a,b){return Wb(this.a,b,this.a[this.K],this.K+1)};f.R=function(a,b,c){return Wb(this.a,b,c,this.K)};function Kc(a,b,c,d){this.ga=a;this.ka=b;this.m=c;this.l=d;this.j=31850732;this.v=1536}f=Kc.prototype;f.toString=function(){return ob(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.m};
f.X=function(){if(1<Ba(this.ga))return new Kc(hb(this.ga),this.ka,this.m,null);var a=Xa(this.ka);return null==a?null:a};f.D=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.S=function(){return F.b(this.ga,0)};f.Z=function(){return 1<Ba(this.ga)?new Kc(hb(this.ga),this.ka,this.m,null):null==this.ka?O:this.ka};f.M=function(){return this};f.cb=function(){return this.ga};f.eb=function(){return null==this.ka?O:this.ka};
f.I=function(a,b){return new Kc(this.ga,this.ka,b,this.l)};f.L=function(a,b){return U(b,this)};f.bb=function(){return null==this.ka?null:this.ka};Kc.prototype[ra]=function(){return S(this)};function Lc(a,b){return 0===Ba(a)?b:new Kc(a,b,null,null)}function Nc(a,b){a.add(b)}function Oc(a){for(var b=[];;)if(L(a))b.push(N(a)),a=P(a);else return b}function Pc(a,b){if(Xb(a))return dc(a);for(var c=a,d=b,e=0;;)if(0<d&&L(c))c=P(c),--d,e+=1;else return e}
var Qc=function Qc(b){return null==b?null:null==P(b)?L(N(b)):U(N(b),Qc(P(b)))},Rc=function Rc(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 0:return Rc.B();case 1:return Rc.c(arguments[0]);case 2:return Rc.b(arguments[0],arguments[1]);default:return Rc.A(arguments[0],arguments[1],new M(c.slice(2),0))}};Rc.B=function(){return new Gc(null,function(){return null},null,null)};Rc.c=function(a){return new Gc(null,function(){return a},null,null)};
Rc.b=function(a,b){return new Gc(null,function(){var c=L(a);return c?pc(c)?Lc(ib(c),Rc.b(jb(c),b)):U(N(c),Rc.b(Kb(c),b)):b},null,null)};Rc.A=function(a,b,c){return function e(a,b){return new Gc(null,function(){var c=L(a);return c?pc(c)?Lc(ib(c),e(jb(c),b)):U(N(c),e(Kb(c),b)):x(b)?e(N(b),P(b)):null},null,null)}(Rc.b(a,b),c)};Rc.J=function(a){var b=N(a),c=P(a);a=N(c);c=P(c);return Rc.A(b,a,c)};Rc.T=2;
function Sc(a,b,c){var d=L(c);if(0===b)return a.B?a.B():a.call(null);c=G(d);var e=H(d);if(1===b)return a.c?a.c(c):a.c?a.c(c):a.call(null,c);var d=G(e),g=H(e);if(2===b)return a.b?a.b(c,d):a.b?a.b(c,d):a.call(null,c,d);var e=G(g),h=H(g);if(3===b)return a.g?a.g(c,d,e):a.g?a.g(c,d,e):a.call(null,c,d,e);var g=G(h),k=H(h);if(4===b)return a.aa?a.aa(c,d,e,g):a.aa?a.aa(c,d,e,g):a.call(null,c,d,e,g);var h=G(k),l=H(k);if(5===b)return a.Y?a.Y(c,d,e,g,h):a.Y?a.Y(c,d,e,g,h):a.call(null,c,d,e,g,h);var k=G(l),m=
H(l);if(6===b)return a.ya?a.ya(c,d,e,g,h,k):a.ya?a.ya(c,d,e,g,h,k):a.call(null,c,d,e,g,h,k);var l=G(m),n=H(m);if(7===b)return a.za?a.za(c,d,e,g,h,k,l):a.za?a.za(c,d,e,g,h,k,l):a.call(null,c,d,e,g,h,k,l);var m=G(n),p=H(n);if(8===b)return a.Aa?a.Aa(c,d,e,g,h,k,l,m):a.Aa?a.Aa(c,d,e,g,h,k,l,m):a.call(null,c,d,e,g,h,k,l,m);var n=G(p),q=H(p);if(9===b)return a.Ba?a.Ba(c,d,e,g,h,k,l,m,n):a.Ba?a.Ba(c,d,e,g,h,k,l,m,n):a.call(null,c,d,e,g,h,k,l,m,n);var p=G(q),r=H(q);if(10===b)return a.na?a.na(c,d,e,g,h,k,l,
m,n,p):a.na?a.na(c,d,e,g,h,k,l,m,n,p):a.call(null,c,d,e,g,h,k,l,m,n,p);var q=G(r),u=H(r);if(11===b)return a.oa?a.oa(c,d,e,g,h,k,l,m,n,p,q):a.oa?a.oa(c,d,e,g,h,k,l,m,n,p,q):a.call(null,c,d,e,g,h,k,l,m,n,p,q);var r=G(u),v=H(u);if(12===b)return a.pa?a.pa(c,d,e,g,h,k,l,m,n,p,q,r):a.pa?a.pa(c,d,e,g,h,k,l,m,n,p,q,r):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r);var u=G(v),y=H(v);if(13===b)return a.qa?a.qa(c,d,e,g,h,k,l,m,n,p,q,r,u):a.qa?a.qa(c,d,e,g,h,k,l,m,n,p,q,r,u):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,u);var v=
G(y),B=H(y);if(14===b)return a.ra?a.ra(c,d,e,g,h,k,l,m,n,p,q,r,u,v):a.ra?a.ra(c,d,e,g,h,k,l,m,n,p,q,r,u,v):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,u,v);var y=G(B),D=H(B);if(15===b)return a.sa?a.sa(c,d,e,g,h,k,l,m,n,p,q,r,u,v,y):a.sa?a.sa(c,d,e,g,h,k,l,m,n,p,q,r,u,v,y):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y);var B=G(D),J=H(D);if(16===b)return a.ta?a.ta(c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B):a.ta?a.ta(c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B);var D=G(J),ba=H(J);if(17===
b)return a.ua?a.ua(c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D):a.ua?a.ua(c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D);var J=G(ba),bb=H(ba);if(18===b)return a.va?a.va(c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D,J):a.va?a.va(c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D,J):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D,J);ba=G(bb);bb=H(bb);if(19===b)return a.wa?a.wa(c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D,J,ba):a.wa?a.wa(c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D,J,ba):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,u,v,
y,B,D,J,ba);var w=G(bb);H(bb);if(20===b)return a.xa?a.xa(c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D,J,ba,w):a.xa?a.xa(c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D,J,ba,w):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,u,v,y,B,D,J,ba,w);throw Error("Only up to 20 arguments supported on functions");}
function jc(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 2:return Tc(arguments[0],arguments[1]);case 3:return Uc(arguments[0],arguments[1],arguments[2]);case 4:c=arguments[0];b=U(arguments[1],U(arguments[2],arguments[3]));d=c.T;if(c.J)var e=Pc(b,d+1),c=e<=d?Sc(c,e,b):c.J(b);else c=c.apply(c,Oc(b));return c;case 5:return c=arguments[0],b=U(arguments[1],U(arguments[2],U(arguments[3],arguments[4]))),d=c.T,c.J?(e=Pc(b,d+1),c=e<=d?Sc(c,e,b):
c.J(b)):c=c.apply(c,Oc(b)),c;default:return c=arguments[0],b=U(arguments[1],U(arguments[2],U(arguments[3],U(arguments[4],Qc(new M(b.slice(5),0)))))),d=c.T,c.J?(e=Pc(b,d+1),c=e<=d?Sc(c,e,b):c.J(b)):c=c.apply(c,Oc(b)),c}}function Tc(a,b){var c=a.T;if(a.J){var d=Pc(b,c+1);return d<=c?Sc(a,d,b):a.J(b)}return a.apply(a,Oc(b))}function Uc(a,b,c){b=U(b,c);c=a.T;if(a.J){var d=Pc(b,c+1);return d<=c?Sc(a,d,b):a.J(b)}return a.apply(a,Oc(b))}
var Vc=function Vc(){"undefined"===typeof ha&&(ha=function(b,c){this.Bb=b;this.Ab=c;this.j=393216;this.v=0},ha.prototype.I=function(b,c){return new ha(this.Bb,c)},ha.prototype.H=function(){return this.Ab},ha.prototype.fa=function(){return!1},ha.prototype.next=function(){return Error("No such element")},ha.prototype.remove=function(){return Error("Unsupported operation")},ha.Jb=function(){return new X(null,2,5,Wc,[kc(Xc,new pb(null,1,[Yc,Cc(Zc,Cc(cc))],null)),$c],null)},ha.nb=!0,ha.Za="cljs.core/t_cljs$core10179",
ha.zb=function(b){return K(b,"cljs.core/t_cljs$core10179")});return new ha(Vc,ad)};function bd(a,b){for(;;){if(null==L(b))return!0;var c;c=N(b);c=a.c?a.c(c):a.call(null,c);if(x(c)){c=a;var d=P(b);a=c;b=d}else return!1}}
var Y=function Y(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 1:return Y.c(arguments[0]);case 2:return Y.b(arguments[0],arguments[1]);case 3:return Y.g(arguments[0],arguments[1],arguments[2]);case 4:return Y.aa(arguments[0],arguments[1],arguments[2],arguments[3]);default:return Y.A(arguments[0],arguments[1],arguments[2],arguments[3],new M(c.slice(4),0))}};
Y.c=function(a){return function(b){return function(){function c(c,d){var e=a.c?a.c(d):a.call(null,d);return b.b?b.b(c,e):b.call(null,c,e)}function d(a){return b.c?b.c(a):b.call(null,a)}function e(){return b.B?b.B():b.call(null)}var g=null,h=function(){function c(a,b,e){var g=null;if(2<arguments.length){for(var g=0,h=Array(arguments.length-2);g<h.length;)h[g]=arguments[g+2],++g;g=new M(h,0)}return d.call(this,a,b,g)}function d(c,e,g){e=Uc(a,e,g);return b.b?b.b(c,e):b.call(null,c,e)}c.T=2;c.J=function(a){var b=
N(a);a=P(a);var c=N(a);a=Kb(a);return d(b,c,a)};c.A=d;return c}(),g=function(a,b,g){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,a);case 2:return c.call(this,a,b);default:var n=null;if(2<arguments.length){for(var n=0,p=Array(arguments.length-2);n<p.length;)p[n]=arguments[n+2],++n;n=new M(p,0)}return h.A(a,b,n)}throw Error("Invalid arity: "+arguments.length);};g.T=2;g.J=h.J;g.B=e;g.c=d;g.b=c;g.A=h.A;return g}()}};
Y.b=function(a,b){return new Gc(null,function(){var c=L(b);if(c){if(pc(c)){for(var d=ib(c),e=dc(d),g=new Ic(Array(e),0),h=0;;)if(h<e)Nc(g,function(){var b=F.b(d,h);return a.c?a.c(b):a.call(null,b)}()),h+=1;else break;return Lc(g.ga(),Y.b(a,jb(c)))}return U(function(){var b=N(c);return a.c?a.c(b):a.call(null,b)}(),Y.b(a,Kb(c)))}return null},null,null)};
Y.g=function(a,b,c){return new Gc(null,function(){var d=L(b),e=L(c);if(d&&e){var g=U,h;h=N(d);var k=N(e);h=a.b?a.b(h,k):a.call(null,h,k);d=g(h,Y.g(a,Kb(d),Kb(e)))}else d=null;return d},null,null)};Y.aa=function(a,b,c,d){return new Gc(null,function(){var e=L(b),g=L(c),h=L(d);if(e&&g&&h){var k=U,l;l=N(e);var m=N(g),n=N(h);l=a.g?a.g(l,m,n):a.call(null,l,m,n);e=k(l,Y.aa(a,Kb(e),Kb(g),Kb(h)))}else e=null;return e},null,null)};
Y.A=function(a,b,c,d,e){var g=function k(a){return new Gc(null,function(){var b=Y.b(L,a);return bd(xc,b)?U(Y.b(N,b),k(Y.b(Kb,b))):null},null,null)};return Y.b(function(){return function(b){return Tc(a,b)}}(g),g(bc.A(e,d,ac([c,b],0))))};Y.J=function(a){var b=N(a),c=P(a);a=N(c);var d=P(c),c=N(d),e=P(d),d=N(e),e=P(e);return Y.A(b,a,c,d,e)};Y.T=4;function cd(a,b){this.w=a;this.a=b}
function dd(a){return new cd(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function ed(a){a=a.h;return 32>a?0:a-1>>>5<<5}function fd(a,b,c){for(;;){if(0===b)return c;var d=dd(a);d.a[0]=c;c=d;b-=5}}var gd=function gd(b,c,d,e){var g=new cd(d.w,E(d.a)),h=b.h-1>>>c&31;5===c?g.a[h]=e:(d=d.a[h],b=null!=d?gd(b,c-5,d,e):fd(null,c-5,e),g.a[h]=b);return g};
function hd(a,b){throw Error([C("No item "),C(a),C(" in vector of length "),C(b)].join(""));}function id(a,b){if(b>=ed(a))return a.V;for(var c=a.root,d=a.shift;;)if(0<d)var e=d-5,c=c.a[b>>>d&31],d=e;else return c.a}function jd(a,b){return 0<=b&&b<a.h?id(a,b):hd(b,a.h)}var kd=function kd(b,c,d,e,g){var h=new cd(d.w,E(d.a));if(0===c)h.a[e&31]=g;else{var k=e>>>c&31;b=kd(b,c-5,d.a[k],e,g);h.a[k]=b}return h};function ld(a,b,c,d,e,g){this.i=a;this.$a=b;this.a=c;this.la=d;this.start=e;this.end=g}
ld.prototype.fa=function(){return this.i<this.end};ld.prototype.next=function(){32===this.i-this.$a&&(this.a=id(this.la,this.i),this.$a+=32);var a=this.a[this.i&31];this.i+=1;return a};function X(a,b,c,d,e,g){this.m=a;this.h=b;this.shift=c;this.root=d;this.V=e;this.l=g;this.j=167668511;this.v=8196}f=X.prototype;f.toString=function(){return ob(this)};f.equiv=function(a){return this.o(null,a)};f.N=function(a,b){return I.g(this,b,null)};f.F=function(a,b,c){return"number"===typeof b?F.g(this,b,c):c};
f.W=function(a,b){return jd(this,b)[b&31]};f.ba=function(a,b,c){return 0<=b&&b<this.h?id(this,b)[b&31]:c};f.ib=function(a,b,c){if(0<=b&&b<this.h)return ed(this)<=b?(a=E(this.V),a[b&31]=c,new X(this.m,this.h,this.shift,this.root,a,null)):new X(this.m,this.h,this.shift,kd(this,this.shift,this.root,b,c),this.V,null);if(b===this.h)return Ca(this,c);throw Error([C("Index "),C(b),C(" out of bounds  [0,"),C(this.h),C("]")].join(""));};
f.Ca=function(){var a=this.h;return new ld(0,0,0<dc(this)?id(this,0):null,this,0,a)};f.H=function(){return this.m};f.U=function(){return this.h};f.fb=function(){return F.b(this,0)};f.gb=function(){return F.b(this,1)};f.D=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){if(b instanceof X)if(this.h===dc(b))for(var c=mb(this),d=mb(b);;)if(x(c.fa())){var e=c.next(),g=d.next();if(!Q.b(e,g))return!1}else return!0;else return!1;else return Zb(this,b)};
f.Ua=function(){return new md(this.h,this.shift,nd.c?nd.c(this.root):nd.call(null,this.root),od.c?od.c(this.V):od.call(null,this.V))};f.P=function(a,b){return Rb(this,b)};f.R=function(a,b,c){a=0;for(var d=c;;)if(a<this.h){var e=id(this,a);c=e.length;a:for(var g=0;;)if(g<c)var h=e[g],d=b.b?b.b(d,h):b.call(null,d,h),g=g+1;else{e=d;break a}a+=c;d=e}else return d};f.Pa=function(a,b,c){if("number"===typeof b)return Oa(this,b,c);throw Error("Vector's key for assoc must be a number.");};
f.M=function(){if(0===this.h)return null;if(32>=this.h)return new M(this.V,0);var a;a:{a=this.root;for(var b=this.shift;;)if(0<b)b-=5,a=a.a[0];else{a=a.a;break a}}return pd?pd(this,a,0,0):qd.call(null,this,a,0,0)};f.I=function(a,b){return new X(b,this.h,this.shift,this.root,this.V,this.l)};
f.L=function(a,b){if(32>this.h-ed(this)){for(var c=this.V.length,d=Array(c+1),e=0;;)if(e<c)d[e]=this.V[e],e+=1;else break;d[c]=b;return new X(this.m,this.h+1,this.shift,this.root,d,null)}c=(d=this.h>>>5>1<<this.shift)?this.shift+5:this.shift;d?(d=dd(null),d.a[0]=this.root,e=fd(null,this.shift,new cd(null,this.V)),d.a[1]=e):d=gd(this,this.shift,this.root,new cd(null,this.V));return new X(this.m,this.h+1,c,d,[b],null)};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.W(null,c);case 3:return this.ba(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.b=function(a,c){return this.W(null,c)};a.g=function(a,c,d){return this.ba(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.c=function(a){return this.W(null,a)};f.b=function(a,b){return this.ba(null,a,b)};
var Wc=new cd(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),cc=new X(null,0,5,Wc,[],Ob);X.prototype[ra]=function(){return S(this)};function rd(a,b,c,d,e,g){this.da=a;this.node=b;this.i=c;this.K=d;this.m=e;this.l=g;this.j=32375020;this.v=1536}f=rd.prototype;f.toString=function(){return ob(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.m};
f.X=function(){if(this.K+1<this.node.length){var a;a=this.da;var b=this.node,c=this.i,d=this.K+1;a=pd?pd(a,b,c,d):qd.call(null,a,b,c,d);return null==a?null:a}return kb(this)};f.D=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.P=function(a,b){var c;c=this.da;var d=this.i+this.K,e=dc(this.da);c=sd?sd(c,d,e):td.call(null,c,d,e);return Rb(c,b)};
f.R=function(a,b,c){a=this.da;var d=this.i+this.K,e=dc(this.da);a=sd?sd(a,d,e):td.call(null,a,d,e);return Sb(a,b,c)};f.S=function(){return this.node[this.K]};f.Z=function(){if(this.K+1<this.node.length){var a;a=this.da;var b=this.node,c=this.i,d=this.K+1;a=pd?pd(a,b,c,d):qd.call(null,a,b,c,d);return null==a?O:a}return jb(this)};f.M=function(){return this};f.cb=function(){var a=this.node;return new Jc(a,this.K,a.length)};
f.eb=function(){var a=this.i+this.node.length;if(a<Ba(this.da)){var b=this.da,c=id(this.da,a);return pd?pd(b,c,a,0):qd.call(null,b,c,a,0)}return O};f.I=function(a,b){return ud?ud(this.da,this.node,this.i,this.K,b):qd.call(null,this.da,this.node,this.i,this.K,b)};f.L=function(a,b){return U(b,this)};f.bb=function(){var a=this.i+this.node.length;if(a<Ba(this.da)){var b=this.da,c=id(this.da,a);return pd?pd(b,c,a,0):qd.call(null,b,c,a,0)}return null};rd.prototype[ra]=function(){return S(this)};
function qd(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 3:return b=arguments[0],c=arguments[1],d=arguments[2],new rd(b,jd(b,c),c,d,null,null);case 4:return pd(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return ud(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error([C("Invalid arity: "),C(b.length)].join(""));}}function pd(a,b,c,d){return new rd(a,b,c,d,null,null)}
function ud(a,b,c,d,e){return new rd(a,b,c,d,e,null)}function vd(a,b,c,d,e){this.m=a;this.la=b;this.start=c;this.end=d;this.l=e;this.j=167666463;this.v=8192}f=vd.prototype;f.toString=function(){return ob(this)};f.equiv=function(a){return this.o(null,a)};f.N=function(a,b){return I.g(this,b,null)};f.F=function(a,b,c){return"number"===typeof b?F.g(this,b,c):c};f.W=function(a,b){return 0>b||this.end<=this.start+b?hd(b,this.end-this.start):F.b(this.la,this.start+b)};
f.ba=function(a,b,c){return 0>b||this.end<=this.start+b?c:F.g(this.la,this.start+b,c)};f.ib=function(a,b,c){var d=this.start+b;a=this.m;c=gc.g(this.la,d,c);b=this.start;var e=this.end,d=d+1,d=e>d?e:d;return wd.Y?wd.Y(a,c,b,d,null):wd.call(null,a,c,b,d,null)};f.H=function(){return this.m};f.U=function(){return this.end-this.start};f.D=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.P=function(a,b){return Rb(this,b)};
f.R=function(a,b,c){return Sb(this,b,c)};f.Pa=function(a,b,c){if("number"===typeof b)return Oa(this,b,c);throw Error("Subvec's key for assoc must be a number.");};f.M=function(){var a=this;return function(b){return function d(e){return e===a.end?null:U(F.b(a.la,e),new Gc(null,function(){return function(){return d(e+1)}}(b),null,null))}}(this)(a.start)};f.I=function(a,b){return wd.Y?wd.Y(b,this.la,this.start,this.end,this.l):wd.call(null,b,this.la,this.start,this.end,this.l)};
f.L=function(a,b){var c=this.m,d=Oa(this.la,this.end,b),e=this.start,g=this.end+1;return wd.Y?wd.Y(c,d,e,g,null):wd.call(null,c,d,e,g,null)};f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.W(null,c);case 3:return this.ba(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.b=function(a,c){return this.W(null,c)};a.g=function(a,c,d){return this.ba(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};
f.c=function(a){return this.W(null,a)};f.b=function(a,b){return this.ba(null,a,b)};vd.prototype[ra]=function(){return S(this)};function wd(a,b,c,d,e){for(;;)if(b instanceof vd)c=b.start+c,d=b.start+d,b=b.la;else{var g=dc(b);if(0>c||0>d||c>g||d>g)throw Error("Index out of bounds");return new vd(a,b,c,d,e)}}
function td(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 2:return b=arguments[0],sd(b,arguments[1],dc(b));case 3:return sd(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(b.length)].join(""));}}function sd(a,b,c){return wd(null,a,b,c,null)}function xd(a,b){return a===b.w?b:new cd(a,E(b.a))}function nd(a){return new cd({},E(a.a))}
function od(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];sc(a,0,b,0,a.length);return b}var yd=function yd(b,c,d,e){d=xd(b.root.w,d);var g=b.h-1>>>c&31;if(5===c)b=e;else{var h=d.a[g];b=null!=h?yd(b,c-5,h,e):fd(b.root.w,c-5,e)}d.a[g]=b;return d};function md(a,b,c,d){this.h=a;this.shift=b;this.root=c;this.V=d;this.v=88;this.j=275}f=md.prototype;
f.Xa=function(a,b){if(this.root.w){if(32>this.h-ed(this))this.V[this.h&31]=b;else{var c=new cd(this.root.w,this.V),d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];d[0]=b;this.V=d;if(this.h>>>5>1<<this.shift){var d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],e=this.shift+
5;d[0]=this.root;d[1]=fd(this.root.w,this.shift,c);this.root=new cd(this.root.w,d);this.shift=e}else this.root=yd(this,this.shift,this.root,c)}this.h+=1;return this}throw Error("conj! after persistent!");};f.Ya=function(){if(this.root.w){this.root.w=null;var a=this.h-ed(this),b=Array(a);sc(this.V,0,b,0,a);return new X(null,this.h,this.shift,this.root,b,null)}throw Error("persistent! called twice");};
f.Qa=function(a,b,c){if("number"===typeof b)return gb(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
f.lb=function(a,b,c){var d=this;if(d.root.w){if(0<=b&&b<d.h)return ed(this)<=b?d.V[b&31]=c:(a=function(){return function g(a,k){var l=xd(d.root.w,k);if(0===a)l.a[b&31]=c;else{var m=b>>>a&31,n=g(a-5,l.a[m]);l.a[m]=n}return l}}(this).call(null,d.shift,d.root),d.root=a),this;if(b===d.h)return db(this,c);throw Error([C("Index "),C(b),C(" out of bounds for TransientVector of length"),C(d.h)].join(""));}throw Error("assoc! after persistent!");};
f.U=function(){if(this.root.w)return this.h;throw Error("count after persistent!");};f.W=function(a,b){if(this.root.w)return jd(this,b)[b&31];throw Error("nth after persistent!");};f.ba=function(a,b,c){return 0<=b&&b<this.h?F.b(this,b):c};f.N=function(a,b){return I.g(this,b,null)};f.F=function(a,b,c){return"number"===typeof b?F.g(this,b,c):c};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.N(null,c);case 3:return this.F(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.b=function(a,c){return this.N(null,c)};a.g=function(a,c,d){return this.F(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.c=function(a){return this.N(null,a)};f.b=function(a,b){return this.F(null,a,b)};function zd(){this.j=2097152;this.v=0}
zd.prototype.equiv=function(a){return this.o(null,a)};zd.prototype.o=function(){return!1};var Ad=new zd;function Bd(a,b){return uc(nc(b)?dc(a)===dc(b)?bd(xc,Y.b(function(a){return Q.b(Hb(b,N(a),Ad),N(P(a)))},a)):null:null)}function Cd(a){this.u=a}Cd.prototype.next=function(){if(null!=this.u){var a=N(this.u),b=fc(a,0),a=fc(a,1);this.u=P(this.u);return{value:[b,a],done:!1}}return{value:null,done:!0}};function Dd(a){return new Cd(L(a))}
function Ed(a,b){var c;if(b instanceof V)a:{c=a.length;for(var d=b.Fa,e=0;;){if(c<=e){c=-1;break a}if(a[e]instanceof V&&d===a[e].Fa){c=e;break a}e+=2}}else if("string"==typeof b||"number"===typeof b)a:for(c=a.length,d=0;;){if(c<=d){c=-1;break a}if(b===a[d]){c=d;break a}d+=2}else if(b instanceof Gb)a:for(c=a.length,d=b.Ha,e=0;;){if(c<=e){c=-1;break a}if(a[e]instanceof Gb&&d===a[e].Ha){c=e;break a}e+=2}else if(null==b)a:for(c=a.length,d=0;;){if(c<=d){c=-1;break a}if(null==a[d]){c=d;break a}d+=2}else a:for(c=
a.length,d=0;;){if(c<=d){c=-1;break a}if(Q.b(b,a[d])){c=d;break a}d+=2}return c}function Fd(a,b,c){this.a=a;this.i=b;this.ea=c;this.j=32374990;this.v=0}f=Fd.prototype;f.toString=function(){return ob(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.ea};f.X=function(){return this.i<this.a.length-2?new Fd(this.a,this.i+2,this.ea):null};f.U=function(){return(this.a.length-this.i)/2};f.D=function(){return Nb(this)};f.o=function(a,b){return Zb(this,b)};
f.P=function(a,b){return vc(b,this)};f.R=function(a,b,c){return wc(b,c,this)};f.S=function(){return new X(null,2,5,Wc,[this.a[this.i],this.a[this.i+1]],null)};f.Z=function(){return this.i<this.a.length-2?new Fd(this.a,this.i+2,this.ea):O};f.M=function(){return this};f.I=function(a,b){return new Fd(this.a,this.i,b)};f.L=function(a,b){return U(b,this)};Fd.prototype[ra]=function(){return S(this)};function Gd(a,b,c){this.a=a;this.i=b;this.h=c}Gd.prototype.fa=function(){return this.i<this.h};
Gd.prototype.next=function(){var a=new X(null,2,5,Wc,[this.a[this.i],this.a[this.i+1]],null);this.i+=2;return a};function pb(a,b,c,d){this.m=a;this.h=b;this.a=c;this.l=d;this.j=16647951;this.v=8196}f=pb.prototype;f.toString=function(){return ob(this)};f.equiv=function(a){return this.o(null,a)};f.keys=function(){return S(Hd.c?Hd.c(this):Hd.call(null,this))};f.entries=function(){return Dd(L(this))};f.values=function(){return S(Jd.c?Jd.c(this):Jd.call(null,this))};
f.has=function(a){return Hb(this,a,tc)===tc?!1:!0};f.get=function(a,b){return this.F(null,a,b)};f.forEach=function(a){for(var b=L(this),c=null,d=0,e=0;;)if(e<d){var g=c.W(null,e),h=fc(g,0),g=fc(g,1);a.b?a.b(g,h):a.call(null,g,h);e+=1}else if(b=L(b))pc(b)?(c=ib(b),b=jb(b),h=c,d=dc(c),c=h):(c=N(b),h=fc(c,0),g=fc(c,1),a.b?a.b(g,h):a.call(null,g,h),b=P(b),c=null,d=0),e=0;else return null};f.N=function(a,b){return I.g(this,b,null)};f.F=function(a,b,c){a=Ed(this.a,b);return-1===a?c:this.a[a+1]};
f.Ca=function(){return new Gd(this.a,0,2*this.h)};f.H=function(){return this.m};f.U=function(){return this.h};f.D=function(){var a=this.l;return null!=a?a:this.l=a=Pb(this)};f.o=function(a,b){if(null!=b&&(b.j&1024||b.tb)){var c=this.a.length;if(this.h===b.U(null))for(var d=0;;)if(d<c){var e=b.F(null,this.a[d],tc);if(e!==tc)if(Q.b(this.a[d+1],e))d+=2;else return!1;else return!1}else return!0;else return!1}else return Bd(this,b)};f.Ua=function(){return new Kd({},this.a.length,E(this.a))};
f.P=function(a,b){return vc(b,this)};f.R=function(a,b,c){return wc(b,c,this)};f.Pa=function(a,b,c){a=Ed(this.a,b);if(-1===a){if(this.h<Ld){a=this.a;for(var d=a.length,e=Array(d+2),g=0;;)if(g<d)e[g]=a[g],g+=1;else break;e[d]=b;e[d+1]=c;return new pb(this.m,this.h+1,e,null)}a=hc;null!=a?null!=a&&(a.v&4||a.Eb)?(d=ya(db,cb(a),this),d=eb(d),a=kc(d,lc(a))):a=ya(Ca,a,this):a=ya(bc,O,this);return Ra(Ha(a,b,c),this.m)}if(c===this.a[a+1])return this;b=E(this.a);b[a+1]=c;return new pb(this.m,this.h,b,null)};
f.M=function(){var a=this.a;return 0<=a.length-2?new Fd(a,0,null):null};f.I=function(a,b){return new pb(b,this.h,this.a,this.l)};f.L=function(a,b){if(oc(b))return Ha(this,F.b(b,0),F.b(b,1));for(var c=this,d=L(b);;){if(null==d)return c;var e=N(d);if(oc(e))c=Ha(c,F.b(e,0),F.b(e,1)),d=P(d);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.N(null,c);case 3:return this.F(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.b=function(a,c){return this.N(null,c)};a.g=function(a,c,d){return this.F(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.c=function(a){return this.N(null,a)};f.b=function(a,b){return this.F(null,a,b)};var ad=new pb(null,0,[],Qb),Ld=8;pb.prototype[ra]=function(){return S(this)};
function Kd(a,b,c){this.Na=a;this.La=b;this.a=c;this.j=258;this.v=56}f=Kd.prototype;f.U=function(){if(x(this.Na))return yc(this.La);throw Error("count after persistent!");};f.N=function(a,b){return I.g(this,b,null)};f.F=function(a,b,c){if(x(this.Na))return a=Ed(this.a,b),-1===a?c:this.a[a+1];throw Error("lookup after persistent!");};
f.Xa=function(a,b){if(x(this.Na)){if(null!=b?b.j&2048||b.ub||(b.j?0:z(Ja,b)):z(Ja,b))return fb(this,Md.c?Md.c(b):Md.call(null,b),Nd.c?Nd.c(b):Nd.call(null,b));for(var c=L(b),d=this;;){var e=N(c);if(x(e))c=P(c),d=fb(d,Md.c?Md.c(e):Md.call(null,e),Nd.c?Nd.c(e):Nd.call(null,e));else return d}}else throw Error("conj! after persistent!");};f.Ya=function(){if(x(this.Na))return this.Na=!1,new pb(null,yc(this.La),this.a,null);throw Error("persistent! called twice");};
f.Qa=function(a,b,c){if(x(this.Na)){a=Ed(this.a,b);if(-1===a){if(this.La+2<=2*Ld)return this.La+=2,this.a.push(b),this.a.push(c),this;a=Od.b?Od.b(this.La,this.a):Od.call(null,this.La,this.a);return fb(a,b,c)}c!==this.a[a+1]&&(this.a[a+1]=c);return this}throw Error("assoc! after persistent!");};function Od(a,b){for(var c=cb(hc),d=0;;)if(d<a)c=fb(c,b[d],b[d+1]),d+=2;else return c}function Pd(){this.ma=!1}
function Qd(a,b){return a===b?!0:a===b||a instanceof V&&b instanceof V&&a.Fa===b.Fa?!0:Q.b(a,b)}function Rd(a,b,c){a=E(a);a[b]=c;return a}function Sd(a,b,c,d){a=a.Ja(b);a.a[c]=d;return a}function Td(a,b,c,d){this.a=a;this.i=b;this.Sa=c;this.ja=d}Td.prototype.advance=function(){for(var a=this.a.length;;)if(this.i<a){var b=this.a[this.i],c=this.a[this.i+1];null!=b?b=this.Sa=new X(null,2,5,Wc,[b,c],null):null!=c?(b=mb(c),b=b.fa()?this.ja=b:!1):b=!1;this.i+=2;if(b)return!0}else return!1};
Td.prototype.fa=function(){var a=null!=this.Sa;return a?a:(a=null!=this.ja)?a:this.advance()};Td.prototype.next=function(){if(null!=this.Sa){var a=this.Sa;this.Sa=null;return a}if(null!=this.ja)return a=this.ja.next(),this.ja.fa()||(this.ja=null),a;if(this.advance())return this.next();throw Error("No such element");};Td.prototype.remove=function(){return Error("Unsupported operation")};function Ud(a,b,c){this.w=a;this.G=b;this.a=c}f=Ud.prototype;
f.Ja=function(a){if(a===this.w)return this;var b=zc(this.G),c=Array(0>b?4:2*(b+1));sc(this.a,0,c,0,2*b);return new Ud(a,this.G,c)};f.Ra=function(){return Vd?Vd(this.a):Wd.call(null,this.a)};f.Ka=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.G&e))return d;var g=zc(this.G&e-1),e=this.a[2*g],g=this.a[2*g+1];return null==e?g.Ka(a+5,b,c,d):Qd(c,e)?g:d};
f.ia=function(a,b,c,d,e,g){var h=1<<(c>>>b&31),k=zc(this.G&h-1);if(0===(this.G&h)){var l=zc(this.G);if(2*l<this.a.length){a=this.Ja(a);b=a.a;g.ma=!0;a:for(c=2*(l-k),g=2*k+(c-1),l=2*(k+1)+(c-1);;){if(0===c)break a;b[l]=b[g];--l;--c;--g}b[2*k]=d;b[2*k+1]=e;a.G|=h;return a}if(16<=l){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=Xd.ia(a,b+5,c,d,e,g);for(e=d=0;;)if(32>d)0!==
(this.G>>>d&1)&&(k[d]=null!=this.a[e]?Xd.ia(a,b+5,Eb(this.a[e]),this.a[e],this.a[e+1],g):this.a[e+1],e+=2),d+=1;else break;return new Yd(a,l+1,k)}b=Array(2*(l+4));sc(this.a,0,b,0,2*k);b[2*k]=d;b[2*k+1]=e;sc(this.a,2*k,b,2*(k+1),2*(l-k));g.ma=!0;a=this.Ja(a);a.a=b;a.G|=h;return a}l=this.a[2*k];h=this.a[2*k+1];if(null==l)return l=h.ia(a,b+5,c,d,e,g),l===h?this:Sd(this,a,2*k+1,l);if(Qd(d,l))return e===h?this:Sd(this,a,2*k+1,e);g.ma=!0;g=b+5;d=Zd?Zd(a,g,l,h,c,d,e):$d.call(null,a,g,l,h,c,d,e);e=2*k;k=
2*k+1;a=this.Ja(a);a.a[e]=null;a.a[k]=d;return a};
f.ha=function(a,b,c,d,e){var g=1<<(b>>>a&31),h=zc(this.G&g-1);if(0===(this.G&g)){var k=zc(this.G);if(16<=k){h=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];h[b>>>a&31]=Xd.ha(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0!==(this.G>>>c&1)&&(h[c]=null!=this.a[d]?Xd.ha(a+5,Eb(this.a[d]),this.a[d],this.a[d+1],e):this.a[d+1],d+=2),c+=1;else break;return new Yd(null,k+1,h)}a=Array(2*(k+1));sc(this.a,
0,a,0,2*h);a[2*h]=c;a[2*h+1]=d;sc(this.a,2*h,a,2*(h+1),2*(k-h));e.ma=!0;return new Ud(null,this.G|g,a)}var l=this.a[2*h],g=this.a[2*h+1];if(null==l)return k=g.ha(a+5,b,c,d,e),k===g?this:new Ud(null,this.G,Rd(this.a,2*h+1,k));if(Qd(c,l))return d===g?this:new Ud(null,this.G,Rd(this.a,2*h+1,d));e.ma=!0;e=this.G;k=this.a;a+=5;a=ae?ae(a,l,g,b,c,d):$d.call(null,a,l,g,b,c,d);c=2*h;h=2*h+1;d=E(k);d[c]=null;d[h]=a;return new Ud(null,e,d)};f.Ca=function(){return new Td(this.a,0,null,null)};
var Xd=new Ud(null,0,[]);function be(a,b,c){this.a=a;this.i=b;this.ja=c}be.prototype.fa=function(){for(var a=this.a.length;;){if(null!=this.ja&&this.ja.fa())return!0;if(this.i<a){var b=this.a[this.i];this.i+=1;null!=b&&(this.ja=mb(b))}else return!1}};be.prototype.next=function(){if(this.fa())return this.ja.next();throw Error("No such element");};be.prototype.remove=function(){return Error("Unsupported operation")};function Yd(a,b,c){this.w=a;this.h=b;this.a=c}f=Yd.prototype;
f.Ja=function(a){return a===this.w?this:new Yd(a,this.h,E(this.a))};f.Ra=function(){return ce?ce(this.a):de.call(null,this.a)};f.Ka=function(a,b,c,d){var e=this.a[b>>>a&31];return null!=e?e.Ka(a+5,b,c,d):d};f.ia=function(a,b,c,d,e,g){var h=c>>>b&31,k=this.a[h];if(null==k)return a=Sd(this,a,h,Xd.ia(a,b+5,c,d,e,g)),a.h+=1,a;b=k.ia(a,b+5,c,d,e,g);return b===k?this:Sd(this,a,h,b)};
f.ha=function(a,b,c,d,e){var g=b>>>a&31,h=this.a[g];if(null==h)return new Yd(null,this.h+1,Rd(this.a,g,Xd.ha(a+5,b,c,d,e)));a=h.ha(a+5,b,c,d,e);return a===h?this:new Yd(null,this.h,Rd(this.a,g,a))};f.Ca=function(){return new be(this.a,0,null)};function ee(a,b,c){b*=2;for(var d=0;;)if(d<b){if(Qd(c,a[d]))return d;d+=2}else return-1}function fe(a,b,c,d){this.w=a;this.Ea=b;this.h=c;this.a=d}f=fe.prototype;
f.Ja=function(a){if(a===this.w)return this;var b=Array(2*(this.h+1));sc(this.a,0,b,0,2*this.h);return new fe(a,this.Ea,this.h,b)};f.Ra=function(){return Vd?Vd(this.a):Wd.call(null,this.a)};f.Ka=function(a,b,c,d){a=ee(this.a,this.h,c);return 0>a?d:Qd(c,this.a[a])?this.a[a+1]:d};
f.ia=function(a,b,c,d,e,g){if(c===this.Ea){b=ee(this.a,this.h,d);if(-1===b){if(this.a.length>2*this.h)return b=2*this.h,c=2*this.h+1,a=this.Ja(a),a.a[b]=d,a.a[c]=e,g.ma=!0,a.h+=1,a;c=this.a.length;b=Array(c+2);sc(this.a,0,b,0,c);b[c]=d;b[c+1]=e;g.ma=!0;d=this.h+1;a===this.w?(this.a=b,this.h=d,a=this):a=new fe(this.w,this.Ea,d,b);return a}return this.a[b+1]===e?this:Sd(this,a,b+1,e)}return(new Ud(a,1<<(this.Ea>>>b&31),[null,this,null,null])).ia(a,b,c,d,e,g)};
f.ha=function(a,b,c,d,e){return b===this.Ea?(a=ee(this.a,this.h,c),-1===a?(a=2*this.h,b=Array(a+2),sc(this.a,0,b,0,a),b[a]=c,b[a+1]=d,e.ma=!0,new fe(null,this.Ea,this.h+1,b)):Q.b(this.a[a],d)?this:new fe(null,this.Ea,this.h,Rd(this.a,a+1,d))):(new Ud(null,1<<(this.Ea>>>a&31),[null,this])).ha(a,b,c,d,e)};f.Ca=function(){return new Td(this.a,0,null,null)};
function $d(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 6:return ae(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);case 7:return Zd(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6]);default:throw Error([C("Invalid arity: "),C(b.length)].join(""));}}
function ae(a,b,c,d,e,g){var h=Eb(b);if(h===d)return new fe(null,h,2,[b,c,e,g]);var k=new Pd;return Xd.ha(a,h,b,c,k).ha(a,d,e,g,k)}function Zd(a,b,c,d,e,g,h){var k=Eb(c);if(k===e)return new fe(null,k,2,[c,d,g,h]);var l=new Pd;return Xd.ia(a,b,k,c,d,l).ia(a,b,e,g,h,l)}function ge(a,b,c,d,e){this.m=a;this.Ga=b;this.i=c;this.u=d;this.l=e;this.j=32374860;this.v=0}f=ge.prototype;f.toString=function(){return ob(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.m};
f.D=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.P=function(a,b){return vc(b,this)};f.R=function(a,b,c){return wc(b,c,this)};f.S=function(){return null==this.u?new X(null,2,5,Wc,[this.Ga[this.i],this.Ga[this.i+1]],null):N(this.u)};f.Z=function(){if(null==this.u){var a=this.Ga,b=this.i+2;return he?he(a,b,null):Wd.call(null,a,b,null)}var a=this.Ga,b=this.i,c=P(this.u);return he?he(a,b,c):Wd.call(null,a,b,c)};f.M=function(){return this};
f.I=function(a,b){return new ge(b,this.Ga,this.i,this.u,this.l)};f.L=function(a,b){return U(b,this)};ge.prototype[ra]=function(){return S(this)};function Wd(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 1:return Vd(arguments[0]);case 3:return he(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(b.length)].join(""));}}function Vd(a){return he(a,0,null)}
function he(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new ge(null,a,b,null,null);var d=a[b+1];if(x(d)&&(d=d.Ra(),x(d)))return new ge(null,a,b+2,d,null);b+=2}else return null;else return new ge(null,a,b,c,null)}function ie(a,b,c,d,e){this.m=a;this.Ga=b;this.i=c;this.u=d;this.l=e;this.j=32374860;this.v=0}f=ie.prototype;f.toString=function(){return ob(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.m};
f.D=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.P=function(a,b){return vc(b,this)};f.R=function(a,b,c){return wc(b,c,this)};f.S=function(){return N(this.u)};f.Z=function(){var a=this.Ga,b=this.i,c=P(this.u);return je?je(null,a,b,c):de.call(null,null,a,b,c)};f.M=function(){return this};f.I=function(a,b){return new ie(b,this.Ga,this.i,this.u,this.l)};f.L=function(a,b){return U(b,this)};ie.prototype[ra]=function(){return S(this)};
function de(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 1:return ce(arguments[0]);case 4:return je(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error([C("Invalid arity: "),C(b.length)].join(""));}}function ce(a){return je(null,a,0,null)}function je(a,b,c,d){if(null==d)for(d=b.length;;)if(c<d){var e=b[c];if(x(e)&&(e=e.Ra(),x(e)))return new ie(a,b,c+1,e,null);c+=1}else return null;else return new ie(a,b,c,d,null)}
function ke(a,b,c){this.$=a;this.ob=b;this.jb=c}ke.prototype.fa=function(){return this.jb&&this.ob.fa()};ke.prototype.next=function(){if(this.jb)return this.ob.next();this.jb=!0;return this.$};ke.prototype.remove=function(){return Error("Unsupported operation")};function le(a,b,c,d,e,g){this.m=a;this.h=b;this.root=c;this.ca=d;this.$=e;this.l=g;this.j=16123663;this.v=8196}f=le.prototype;f.toString=function(){return ob(this)};f.equiv=function(a){return this.o(null,a)};
f.keys=function(){return S(Hd.c?Hd.c(this):Hd.call(null,this))};f.entries=function(){return Dd(L(this))};f.values=function(){return S(Jd.c?Jd.c(this):Jd.call(null,this))};f.has=function(a){return Hb(this,a,tc)===tc?!1:!0};f.get=function(a,b){return this.F(null,a,b)};
f.forEach=function(a){for(var b=L(this),c=null,d=0,e=0;;)if(e<d){var g=c.W(null,e),h=fc(g,0),g=fc(g,1);a.b?a.b(g,h):a.call(null,g,h);e+=1}else if(b=L(b))pc(b)?(c=ib(b),b=jb(b),h=c,d=dc(c),c=h):(c=N(b),h=fc(c,0),g=fc(c,1),a.b?a.b(g,h):a.call(null,g,h),b=P(b),c=null,d=0),e=0;else return null};f.N=function(a,b){return I.g(this,b,null)};f.F=function(a,b,c){return null==b?this.ca?this.$:c:null==this.root?c:this.root.Ka(0,Eb(b),b,c)};
f.Ca=function(){var a=this.root?mb(this.root):Vc;return this.ca?new ke(this.$,a,!1):a};f.H=function(){return this.m};f.U=function(){return this.h};f.D=function(){var a=this.l;return null!=a?a:this.l=a=Pb(this)};f.o=function(a,b){return Bd(this,b)};f.Ua=function(){return new me({},this.root,this.h,this.ca,this.$)};
f.Pa=function(a,b,c){if(null==b)return this.ca&&c===this.$?this:new le(this.m,this.ca?this.h:this.h+1,this.root,!0,c,null);a=new Pd;b=(null==this.root?Xd:this.root).ha(0,Eb(b),b,c,a);return b===this.root?this:new le(this.m,a.ma?this.h+1:this.h,b,this.ca,this.$,null)};f.M=function(){if(0<this.h){var a=null!=this.root?this.root.Ra():null;return this.ca?U(new X(null,2,5,Wc,[null,this.$],null),a):a}return null};f.I=function(a,b){return new le(b,this.h,this.root,this.ca,this.$,this.l)};
f.L=function(a,b){if(oc(b))return Ha(this,F.b(b,0),F.b(b,1));for(var c=this,d=L(b);;){if(null==d)return c;var e=N(d);if(oc(e))c=Ha(c,F.b(e,0),F.b(e,1)),d=P(d);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.N(null,c);case 3:return this.F(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.b=function(a,c){return this.N(null,c)};a.g=function(a,c,d){return this.F(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.c=function(a){return this.N(null,a)};f.b=function(a,b){return this.F(null,a,b)};var hc=new le(null,0,null,!1,null,Qb);le.prototype[ra]=function(){return S(this)};
function me(a,b,c,d,e){this.w=a;this.root=b;this.count=c;this.ca=d;this.$=e;this.j=258;this.v=56}function ne(a,b,c){if(a.w){if(null==b)a.$!==c&&(a.$=c),a.ca||(a.count+=1,a.ca=!0);else{var d=new Pd;b=(null==a.root?Xd:a.root).ia(a.w,0,Eb(b),b,c,d);b!==a.root&&(a.root=b);d.ma&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}f=me.prototype;f.U=function(){if(this.w)return this.count;throw Error("count after persistent!");};
f.N=function(a,b){return null==b?this.ca?this.$:null:null==this.root?null:this.root.Ka(0,Eb(b),b)};f.F=function(a,b,c){return null==b?this.ca?this.$:c:null==this.root?c:this.root.Ka(0,Eb(b),b,c)};
f.Xa=function(a,b){var c;a:if(this.w)if(null!=b?b.j&2048||b.ub||(b.j?0:z(Ja,b)):z(Ja,b))c=ne(this,Md.c?Md.c(b):Md.call(null,b),Nd.c?Nd.c(b):Nd.call(null,b));else{c=L(b);for(var d=this;;){var e=N(c);if(x(e))c=P(c),d=ne(d,Md.c?Md.c(e):Md.call(null,e),Nd.c?Nd.c(e):Nd.call(null,e));else{c=d;break a}}}else throw Error("conj! after persistent");return c};f.Ya=function(){var a;if(this.w)this.w=null,a=new le(null,this.count,this.root,this.ca,this.$,null);else throw Error("persistent! called twice");return a};
f.Qa=function(a,b,c){return ne(this,b,c)};function pe(a,b){this.s=a;this.ea=b;this.j=32374988;this.v=0}f=pe.prototype;f.toString=function(){return ob(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.ea};f.X=function(){var a=(null!=this.s?this.s.j&128||this.s.Wa||(this.s.j?0:z(Ea,this.s)):z(Ea,this.s))?this.s.X(null):P(this.s);return null==a?null:new pe(a,this.ea)};f.D=function(){return Nb(this)};f.o=function(a,b){return Zb(this,b)};f.P=function(a,b){return vc(b,this)};
f.R=function(a,b,c){return wc(b,c,this)};f.S=function(){return this.s.S(null).fb()};f.Z=function(){var a=(null!=this.s?this.s.j&128||this.s.Wa||(this.s.j?0:z(Ea,this.s)):z(Ea,this.s))?this.s.X(null):P(this.s);return null!=a?new pe(a,this.ea):O};f.M=function(){return this};f.I=function(a,b){return new pe(this.s,b)};f.L=function(a,b){return U(b,this)};pe.prototype[ra]=function(){return S(this)};function Hd(a){return(a=L(a))?new pe(a,null):null}function Md(a){return La(a)}
function qe(a,b){this.s=a;this.ea=b;this.j=32374988;this.v=0}f=qe.prototype;f.toString=function(){return ob(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.ea};f.X=function(){var a=(null!=this.s?this.s.j&128||this.s.Wa||(this.s.j?0:z(Ea,this.s)):z(Ea,this.s))?this.s.X(null):P(this.s);return null==a?null:new qe(a,this.ea)};f.D=function(){return Nb(this)};f.o=function(a,b){return Zb(this,b)};f.P=function(a,b){return vc(b,this)};f.R=function(a,b,c){return wc(b,c,this)};
f.S=function(){return this.s.S(null).gb()};f.Z=function(){var a=(null!=this.s?this.s.j&128||this.s.Wa||(this.s.j?0:z(Ea,this.s)):z(Ea,this.s))?this.s.X(null):P(this.s);return null!=a?new qe(a,this.ea):O};f.M=function(){return this};f.I=function(a,b){return new qe(this.s,b)};f.L=function(a,b){return U(b,this)};qe.prototype[ra]=function(){return S(this)};function Jd(a){return(a=L(a))?new qe(a,null):null}function Nd(a){return Ma(a)}
function Fc(a){if(null!=a&&(a.v&4096||a.wb))return a.name;if("string"===typeof a)return a;throw Error([C("Doesn't support name: "),C(a)].join(""));}function re(a,b,c){this.i=a;this.end=b;this.step=c}re.prototype.fa=function(){return 0<this.step?this.i<this.end:this.i>this.end};re.prototype.next=function(){var a=this.i;this.i+=this.step;return a};function se(a,b,c,d,e){this.m=a;this.start=b;this.end=c;this.step=d;this.l=e;this.j=32375006;this.v=8192}f=se.prototype;f.toString=function(){return ob(this)};
f.equiv=function(a){return this.o(null,a)};f.W=function(a,b){if(b<Ba(this))return this.start+b*this.step;if(this.start>this.end&&0===this.step)return this.start;throw Error("Index out of bounds");};f.ba=function(a,b,c){return b<Ba(this)?this.start+b*this.step:this.start>this.end&&0===this.step?this.start:c};f.Ca=function(){return new re(this.start,this.end,this.step)};f.H=function(){return this.m};
f.X=function(){return 0<this.step?this.start+this.step<this.end?new se(this.m,this.start+this.step,this.end,this.step,null):null:this.start+this.step>this.end?new se(this.m,this.start+this.step,this.end,this.step,null):null};f.U=function(){var a=Xa(this);return null==a||!1===a?0:Math.ceil((this.end-this.start)/this.step)};f.D=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.P=function(a,b){return Rb(this,b)};
f.R=function(a,b,c){for(a=this.start;;)if(0<this.step?a<this.end:a>this.end)c=b.b?b.b(c,a):b.call(null,c,a),a+=this.step;else return c};f.S=function(){return null==Xa(this)?null:this.start};f.Z=function(){return null!=Xa(this)?new se(this.m,this.start+this.step,this.end,this.step,null):O};f.M=function(){return 0<this.step?this.start<this.end?this:null:0>this.step?this.start>this.end?this:null:this.start===this.end?null:this};f.I=function(a,b){return new se(b,this.start,this.end,this.step,this.l)};
f.L=function(a,b){return U(b,this)};se.prototype[ra]=function(){return S(this)};function te(a){for(;;)if(L(a))a=P(a);else return null}
function ue(a,b,c,d,e,g,h){var k=la;la=null==la?null:la-1;try{if(null!=la&&0>la)return K(a,"#");K(a,c);if(0===ub.c(g))L(h)&&K(a,function(){var a=ve.c(g);return x(a)?a:"..."}());else{if(L(h)){var l=N(h);b.g?b.g(l,a,g):b.call(null,l,a,g)}for(var m=P(h),n=ub.c(g)-1;;)if(!m||null!=n&&0===n){L(m)&&0===n&&(K(a,d),K(a,function(){var a=ve.c(g);return x(a)?a:"..."}()));break}else{K(a,d);var p=N(m);c=a;h=g;b.g?b.g(p,c,h):b.call(null,p,c,h);var q=P(m);c=n-1;m=q;n=c}}return K(a,e)}finally{la=k}}
function we(a,b){for(var c=L(b),d=null,e=0,g=0;;)if(g<e){var h=d.W(null,g);K(a,h);g+=1}else if(c=L(c))d=c,pc(d)?(c=ib(d),e=jb(d),d=c,h=dc(c),c=e,e=h):(h=N(d),K(a,h),c=P(d),d=null,e=0),g=0;else return null}var xe={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};function ye(a){return[C('"'),C(a.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(a){return xe[a]})),C('"')].join("")}
function ze(a,b){var c=uc(Jb(a,sb));return c?(c=null!=b?b.j&131072||b.vb?!0:!1:!1)?null!=lc(b):c:c}
function Ae(a,b,c){if(null==a)return K(b,"nil");if(ze(c,a)){K(b,"^");var d=lc(a);Z.g?Z.g(d,b,c):Z.call(null,d,b,c);K(b," ")}if(a.nb)return a.zb(b);if(null!=a&&(a.j&2147483648||a.O))return a.C(null,b,c);if(!0===a||!1===a||"number"===typeof a)return K(b,""+C(a));if(null!=a&&a.constructor===Object)return K(b,"#js "),d=Y.b(function(b){return new X(null,2,5,Wc,[Ec.c(b),a[b]],null)},rc(a)),Be.aa?Be.aa(d,Z,b,c):Be.call(null,d,Z,b,c);if(na(a))return ue(b,Z,"#js ["," ","]",c,a);if("string"==typeof a)return x(rb.c(c))?
K(b,ye(a)):K(b,a);if("function"==t(a)){var e=a.name;c=x(function(){var a=null==e;return a?a:/^[\s\xa0]*$/.test(e)}())?"Function":e;return we(b,ac(["#object[",c,' "',""+C(a),'"]'],0))}if(a instanceof Date)return c=function(a,b){for(var c=""+C(a);;)if(dc(c)<b)c=[C("0"),C(c)].join("");else return c},we(b,ac(['#inst "',""+C(a.getUTCFullYear()),"-",c(a.getUTCMonth()+1,2),"-",c(a.getUTCDate(),2),"T",c(a.getUTCHours(),2),":",c(a.getUTCMinutes(),2),":",c(a.getUTCSeconds(),2),".",c(a.getUTCMilliseconds(),
3),"-",'00:00"'],0));if(a instanceof RegExp)return we(b,ac(['#"',a.source,'"'],0));if(null!=a&&(a.j&2147483648||a.O))return $a(a,b,c);if(x(a.constructor.Za))return we(b,ac(["#object[",a.constructor.Za.replace(RegExp("/","g"),"."),"]"],0));e=a.constructor.name;c=x(function(){var a=null==e;return a?a:/^[\s\xa0]*$/.test(e)}())?"Object":e;return we(b,ac(["#object[",c," ",""+C(a),"]"],0))}function Z(a,b,c){var d=Ce.c(c);return x(d)?(c=gc.g(c,De,Ae),d.g?d.g(a,b,c):d.call(null,a,b,c)):Ae(a,b,c)}
function Be(a,b,c,d){return ue(c,function(a,c,d){var k=La(a);b.g?b.g(k,c,d):b.call(null,k,c,d);K(c," ");a=Ma(a);return b.g?b.g(a,c,d):b.call(null,a,c,d)},"{",", ","}",d,L(a))}M.prototype.O=!0;M.prototype.C=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};Gc.prototype.O=!0;Gc.prototype.C=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};ge.prototype.O=!0;ge.prototype.C=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};Fd.prototype.O=!0;
Fd.prototype.C=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};rd.prototype.O=!0;rd.prototype.C=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};Dc.prototype.O=!0;Dc.prototype.C=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};le.prototype.O=!0;le.prototype.C=function(a,b,c){return Be(this,Z,b,c)};ie.prototype.O=!0;ie.prototype.C=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};vd.prototype.O=!0;vd.prototype.C=function(a,b,c){return ue(b,Z,"["," ","]",c,this)};Kc.prototype.O=!0;
Kc.prototype.C=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};qe.prototype.O=!0;qe.prototype.C=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};X.prototype.O=!0;X.prototype.C=function(a,b,c){return ue(b,Z,"["," ","]",c,this)};Bc.prototype.O=!0;Bc.prototype.C=function(a,b){return K(b,"()")};pb.prototype.O=!0;pb.prototype.C=function(a,b,c){return Be(this,Z,b,c)};se.prototype.O=!0;se.prototype.C=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};pe.prototype.O=!0;
pe.prototype.C=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};Ac.prototype.O=!0;Ac.prototype.C=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};var sb=new V(null,"meta","meta",1499536964),tb=new V(null,"dup","dup",556298533),$c=new Gb(null,"meta10180","meta10180",-990168213,null),De=new V(null,"fallback-impl","fallback-impl",-1501286995),qb=new V(null,"flush-on-newline","flush-on-newline",-151457939),rb=new V(null,"readably","readably",1129599760),ve=new V(null,"more-marker","more-marker",-14717935),ub=new V(null,"print-length","print-length",1931866356),Zc=new Gb(null,"quote","quote",1377916282,null),Yc=new V(null,"arglists","arglists",
1661989754),Xc=new Gb(null,"nil-iter","nil-iter",1101030523,null),Ce=new V(null,"alt-impl","alt-impl",670969595);ia=function(){function a(a){var d=null;if(0<arguments.length){for(var d=0,e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new M(e,0)}return b.call(this,d)}function b(a){return console.log.apply(console,xa?ua(a):ta.call(null,a))}a.T=0;a.J=function(a){a=L(a);return b(a)};a.A=b;return a}();
ka=function(){function a(a){var d=null;if(0<arguments.length){for(var d=0,e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new M(e,0)}return b.call(this,d)}function b(a){return console.error.apply(console,xa?ua(a):ta.call(null,a))}a.T=0;a.J=function(a){a=L(a);return b(a)};a.A=b;return a}();
(function(){var a=document.getElementById("mandelbrot");if(x(a)){var b=a.getContext("2d"),c=a.width,d=a.height,e=b.createImageData(c,d),g=e.data;return te(Y.b(function(a,b,c){return function(d){var e=fc(d,0);d=fc(d,1);var g;a:{var q=e/b*3.5-2.5,r=d/c*3-1.5,u=0,v=0;for(g=0;;)if(4>u*u+v*v&&800>g){var y=2*u*v+r;g+=1;u=u*u-v*v+q;v=y}else{r=q=u=255-(.31875*g|0);g*=.00125;g=[C("rgba("),C(q),C(", "),C(r),C(", "),C(u),C(", "),C(g),C(")")].join("");break a}}a.fillStyle=g;return a.fillRect(e,d,1,1)}}(b,c,d,
e,g,a),function(){return function(a,b,c,d,e,g){return function r(u){return new Gc(null,function(a,b,c,d,e,g){return function(){for(var h=u;;){var k=L(h);if(k){var l=k,m=N(l);if(k=L(function(a,b,c,d,e,g,h,k,l,m){return function wa(n){return new Gc(null,function(a,b){return function(){for(;;){var a=L(n);if(a){if(pc(a)){var c=ib(a),d=dc(c),e=new Ic(Array(d),0);a:for(var g=0;;)if(g<d){var h=F.b(c,g);e.add(new X(null,2,5,Wc,[b,h],null));g+=1}else{c=!0;break a}return c?Lc(e.ga(),wa(jb(a))):Lc(e.ga(),null)}e=
N(a);return U(new X(null,2,5,Wc,[b,e],null),wa(Kb(a)))}return null}}}(a,b,c,d,e,g,h,k,l,m),null,null)}}(h,m,l,k,a,b,c,d,e,g)(new se(null,0,c,1,null))))return Rc.b(k,r(Kb(h)));h=Kb(h)}else return null}}}(a,b,c,d,e,g),null,null)}}(b,c,d,e,g,a)(new se(null,0,c,1,null))}()))}return null})();